name: Deploy Multiple React Projects

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'npm'

      # 3. react_01 빌드
      - name: Build react
        working-directory: ./react
        run: |
          npm install
          npm run build
        # SPA fallback 추가
      - name: Add SPA fallback for react
        run: cp ./react/dist/index.html ./react/dist/404.html

      # 4. 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./react/dist
          destination_dir: react

      
